"$schema" = "https://ubcode.useblocks.com/ubproject.schema.json"

[project]
name = "Requirements Playground"
srcdir = "."

[needs]
id_required = true
id_regex = "^[A-Z0-9_]+$"
schema_definitions_from_json = "ubschema.json"

[[needs.types]]
directive = "req"
title = "Requirement"
prefix = "REQ_"

[needs.fields.status]
description = "Bearbeitungsstatus der Anforderung"
schema = { type = "string", enum = ["open", "accepted", "implemented", "deleted"] }
